services:
  app:
    build: .
    environment:
      # all these are read from .env by **docker**
      - BEERMAPPING_APIKEY=${BEERMAPPING_APIKEY}
      - WEATHER_APIKEY=${WEATHER_APIKEY}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      timeout: 1s
      start_period: 5s
      start_interval: 100ms
    restart: unless-stopped
